Repository TFG-nicsanmen-rubsuadav/backend, pull requests merged in 2024-04, with the labels that each got.

#32 feat: pr title checker
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-checker.yml
Labels: backend, CI

#36 feat: add badges readme
  .github/workflows/conventional_commits.yml
  README.md
Labels: backend, CI

#33 feat: register users
  authentication/__init__.py
  authentication/apps.py
  authentication/constants.py
  authentication/migrations/__init__.py
  authentication/models.py
  authentication/tests.py
  authentication/urls.py
  authentication/utils.py
  authentication/views.py
  project/settings.py
  project/urls.py
  requirements.txt
Labels: backend, test

#42 feat: implemented web scrapping
  firebaseConfig.js
  package-lock.json
  package.json
  src/app.js
  src/main/constants.js
  src/main/scrapping.js
  src/main/utils.js
Labels: backend

#49 feat: implemented test cases register users
  .babelrc
  .firebaserc
  .github/workflows/test.yml
  firebase.json
  firebaseConfig.js
  jest.config.cjs
  package-lock.json
  package.json
  src/auth/controllers/register.controller.js
  src/auth/test/createUserAdmin.spec.js
  src/auth/test/getPerofile.spec.js
  src/auth/test/initialCreation.js
  src/auth/test/login.spec.js
  src/auth/test/mainUserForMiddelware.js
  src/auth/test/register.spec.js
  src/auth/test/testNegativeCases.js
  src/auth/test/utils.js
Labels: backend, test

#47 feat: edit user profile validating own user
  src/app.js
  src/auth/controllers/createUser.controller.js
  src/auth/controllers/editUser.controller.js
  src/auth/controllers/register.controller.js
  src/auth/middlewares/checkUpdateProfile.js
  src/auth/routes/editUser.routes.js
  src/auth/routes/profile.routes.js
  src/auth/validators/validations.js
Labels: backend
